### ISSUE TITLE
[OTHER] Add description to label on reviewpad configuration

### ISSUE THREAD

**Issue by ferreiratiago** [EddieHubCommunity/LinkFree#1707]
### What would you like to share?

Right now, the [reviewpad](https://github.com/EddieHubCommunity/LinkFree/blob/main/reviewpad.yml) configuration has labels, but theses labels have no `description`.

The idea of this issue is to add the `description` property to the `labels`.

### Additional information

Suggestion

```yml
labels:
  small:
    description: "" # small description
    color: "294b69"
  medium:
    description: "" # medium description
    color: "a8c3f7"
  large:
    description: "" # large description
    color: "8a2138"
```
