### ISSUE TITLE
[FEATURE] GitHub Action to lock newly created issues

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/LinkFree#6142]
### Description

Unfortunately we have a lot of duplicate comments on new issues that are still awaiting triage from people who have not read the contributing guide, this creates a lot of noise for the maintainers and the community - which then requires more duplicate replies explaining the contributing guide by the maintainers creating even more noise and notifications

I think a way to resolve this might be ...
- new issues are locked by default
- when they are triaged they can be unlocked

Notes ...
- pro: reduced noise of "assign to me" when not been triaged yet
- con: it prevents useful conversation from starting early

Possible GitHub Action https://github.com/marketplace/actions/repo-lockdown

filename `.github/workflows/issue-lock.yaml`
```yaml
name: 'Lock new issues'

on:
  issues:
    types: opened

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v3
        with:
          exclude-issue-labels: "status: ready for dev"
          process-only: "issues"
          skip-closed-issue-comment: true
          issue-comment: >
           To reduce notifications, issues are locked until they are ready for dev and to be assigned
```
