### ISSUE TITLE
[OTHER] Add Repository Condition to GitHub Actions to Prevent Execution in Forked Repositories

### ISSUE THREAD

**Issue by weilincheng** [EddieHubCommunity/LinkFree#6772]
### What would you like to share?

Upon syncing the forked repository, I observed that the `Storybook` and `Deploy releases to Vercel` GitHub Actions were being triggered and subsequently failing. Here's a screenshot for reference:
![image](https://github.com/EddieHubCommunity/LinkFree/assets/7236196/1da6dec2-4e96-4132-a77f-db204fec7d14)

I discovered that these two Actions lack a conditional check to ensure they only run in the `EddieHubCommunity/LinkFree` repository, which leads to these failures in the forked repository. 

To remedy this, I suggest we add the following condition to both GitHub Actions. This will prevent them from executing when the repository is a fork, thereby avoiding unnecessary failures:

```yaml
# .github/workflows/storybook.yml
jobs:
  build:
    if: github.repository == 'EddieHubCommunity/LinkFree'
    runs-on: ubuntu-latest
    steps:
        # steps here...
 
  deploy:
    if: github.repository == 'EddieHubCommunity/LinkFree' && github.event_name != 'pull_request'
    # other properties here...
    steps:
      # steps here...
```

```yaml
# .github/workflows/vercel.yml
jobs:
  deploy:
    if: github.repository == 'EddieHubCommunity/LinkFree'
    runs-on: ubuntu-latest
    steps:
        # steps here...
```

Upon triaging of this issue, I would be glad to implement these changes. Thanks!
